# start by pulling the python image
FROM python:3.8-alpine

# copy the requirements file into the image
COPY ./requirements.txt /catalog_docker/requirements.txt

# switch working directory
WORKDIR /catalog_docker

# install the dependencies and packages in the requirements file
RUN pip install -r requirements.txt

# copy every content from the local file to the image
COPY . /catalog_docker

#Expose the required port
EXPOSE 5001

#Run the command
CMD [ "flask", "run", "--host=0.0.0.0"]